# This workflow will install Python dependencies, run lint with a variety of Python versions
# and check for type errors using MyPy.

name: Lint and Type Checks

on:
  push:
    branches: ["main"]
    paths:
      - "mftools/**"
      - ".github/workflows/lint.yml"
      - "pyproject.toml"
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Type Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --group dev
          python -m pip install .

      - name: Ruff check --output-format=github
        run: |
          ruff check --no-fix --output-format=github

      - name: Ruff format check
        run: |
          ruff format --check --diff

      - name: Run MyPy
        run: |
          mypy --ignore-missing-imports mftools
